import { Course, Testimonial, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Formal Education', icon: 'School' },
  { id: '2', name: 'Business & Finance', icon: 'Wallet' },
  { id: '3', name: 'Creative Arts', icon: 'Palette' },
  { id: '4', name: 'Tech & IT', icon: 'Terminal' },
  { id: '5', name: 'Languages', icon: 'Languages' },
  { id: '6', name: 'Personal Development', icon: 'Brain' },
];

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Accounting 101: Mastering the Ledger in Modern Markets',
    instructor: {
      name: 'David Mensah',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXy8I4Nu2oVtDNlbiQ_4AXJJ7qB5sxggWqx_eAMFgJ89cGJBYcDX39GfBSCEGUeHafIT_EreNLAD6AIIJWkHfSE0BUyb62DO9tHrdKfT9gZJGhNQsJBWVjSHwfrpybxjw7FtAAiWMSRv838tIB_w1N2cvR5ZPxTfaLQEN-B3H3DkBDYY3VjLzR0gk7jhy0fGrM1O690QLSACt6IHOifTcWpD5XHFk9uAVmIiYRItT-0pPDHVDy8c3waaX9lETP_mPnIBgCYSmLnA',
    },
    category: 'Business & Finance',
    rating: 4.9,
    students: '1.2k',
    price: 'KSh 4,500',
    image: 'https://images.pexels.com/photos/5466785/pexels-photo-5466785.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Advanced',
    duration: '6h 44m',
    tool: 'Procreate',
    extraTags: '+23',
    featured: true,
    tag: 'Featured',
  },
  {
    id: '2',
    title: 'Smartphone Photography Masterclass',
    instructor: {
      name: 'Amina Oke',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2LEPaNQYZyctmtPfFqpERg3xylEmFJEdq4YXmKlSbXLeJBfM51qE4UTw9e_UR67X4FjjYEMQn-opamLfwIkLgzWbjAxvzcfuR491a-0Lkr0120DZAPqyPpmdabYiV0zJxIWYgBO44W6R5Mj2S4wdPU-7iZrFumXG7N2-FcfaaoHLCaci1p72fzHM9cdt9MeJJ_PGr2jSpSDVOP24lvNKvTbTg9p72sMa2aj1asmKS7IKUQw7OPz1entXnbNT3svGE0h2JKfcqEQ',
    },
    category: 'Creative Arts',
    rating: 4.8,
    students: '850',
    price: 'KSh 2,800',
    image: 'https://images.pexels.com/photos/3314294/pexels-photo-3314294.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Any level',
    duration: '12h 30m',
    tool: 'Figma',
    extraTags: '+4',
  },
  {
    id: '3',
    title: 'Public Relations: The Modern African Voice',
    instructor: {
      name: 'Zainab Bello',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFBXsJvvNuniTSLKhM8kcb6Rj5OqGEFEY60jmMVt-psWVslr7q7iIAIUTKVspELOcpLTZRvShV672uZYo7Ix9b4BRfOTqSoD3_SqbKaqmsHsxMbdw1XKoX3R8IYHElCGkj8kQQ7CajnbQATRCkVMxk337mmr6Y2WagAvMgDcyI-BlzRrfYm46gz5nspRztvzSd6-ZhfAlCpPF7fXQbN81-NjlsCpxepX7a2hR4wMaYGFoRI31Fycyafu-Lhk4zO09RATrseSz7ew',
    },
    category: 'Formal Education',
    rating: 5.0,
    students: '420',
    price: 'KSh 6,200',
    image: 'https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Beginner',
    duration: '4h 15m',
    tool: 'Python',
    extraTags: '+7',
  },
  {
    id: '4',
    title: 'Python for Beginners: From Zero to African Tech Hero',
    instructor: {
      name: 'Kofi Addo',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCve6wiMi2kUPz6UaZhpqamEeAfkkoTpd2RTVfhYUFUybU4jroswb7E0RVMkCIp-MWUN2yfB_VZUCSczg3dkuqvLipph88kjIixKedt5n0cCNcg49DiwWmM2WZ5IFcy5Lq5GZC0qSyPNO-DXCwppbcZA-BG6_g_f8C75N6dGo-glKFPfDAubRf_UDi3nTcBUaE8kNqGb_sfJRAlzFAsb8ZNCM6D0FjjEb6tJkGRRVlCdjl1aQdWSUNBJF5wM1EkwLqy9pwt2Vz7Vw',
    },
    category: 'Tech & IT',
    rating: 4.7,
    students: '2.5k',
    price: 'KSh 3,500',
    image: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Intermediate',
    duration: '8h 20m',
    tool: 'Excel',
    extraTags: '+2',
  },
  {
    id: '101',
    title: 'Graphic Design Masterclass: Visual Storytelling',
    instructor: {
      name: 'Sarah Mwangi',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFBXsJvvNuniTSLKhM8kcb6Rj5OqGEFEY60jmMVt-psWVslr7q7iIAIUTKVspELOcpLTZRvShV672uZYo7Ix9b4BRfOTqSoD3_SqbKaqmsHsxMbdw1XKoX3R8IYHElCGkj8kQQ7CajnbQATRCkVMxk337mmr6Y2WagAvMgDcyI-BlzRrfYm46gz5nspRztvzSd6-ZhfAlCpPF7fXQbN81-NjlsCpxepX7a2hR4wMaYGFoRI31Fycyafu-Lhk4zO09RATrseSz7ew',
    },
    category: 'Creative Arts',
    rating: 4.9,
    students: '1.2k',
    price: 'KSh 3,800',
    image: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Advanced',
    duration: '2h 5m',
    tool: 'Adobe CC',
    extraTags: '+11',
  },
];

export const ALL_COURSES: Course[] = [
  ...COURSES,
  {
    id: '5',
    title: 'Strategic Business Growth in Lagos',
    instructor: {
      name: 'Chinua Azikiwe',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-1p4L0MBDscikvxeha4-aMR6PXf6nAxsb-U9haagk8bJCquVyLhcQa3Rfy-d57pZVORzgEYZZHbGCu_iIEVCS6QMzzjVWElnYGH4fHUmLAQgSnAuFQLI9r7xPniCMv5QbftuRDHt90GfPJgeJWSfVpwuHntd_DEOedbcVDcqyjXEZtgtxZGRUlyFpgr0Qohf7G8zK_U2gsApX1ABGep6x801qyKUvhAsDYF-wZKHpCMtm-x3lqudJ-Fa1QCvVxlwS6q9Fr-ANFw',
    },
    category: 'Business & Finance',
    rating: 4.8,
    students: '2.4k',
    price: 'KSh 3,200',
    image: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Any level',
    duration: '6h 44m',
    tool: 'DaVinci Resolve',
    extraTags: '+23',
    tag: 'Bestseller',
  },
  {
    id: '6',
    title: 'Full-Stack Web Development',
    instructor: {
      name: 'Sarah Mwangi',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFBXsJvvNuniTSLKhM8kcb6Rj5OqGEFEY60jmMVt-psWVslr7q7iIAIUTKVspELOcpLTZRvShV672uZYo7Ix9b4BRfOTqSoD3_SqbKaqmsHsxMbdw1XKoX3R8IYHElCGkj8kQQ7CajnbQATRCkVMxk337mmr6Y2WagAvMgDcyI-BlzRrfYm46gz5nspRztvzSd6-ZhfAlCpPF7fXQbN81-NjlsCpxepX7a2hR4wMaYGFoRI31Fycyafu-Lhk4zO09RATrseSz7ew',
    },
    category: 'Tech & IT',
    rating: 5.0,
    students: '1.1k',
    price: 'KSh 4,500',
    image: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Beginner',
    duration: '12h 30m',
    tool: 'Procreate',
    extraTags: '+4',
  },
  {
    id: '7',
    title: 'Visual Storytelling & Graphic Arts',
    instructor: {
      name: 'Kofi Mensah',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCve6wiMi2kUPz6UaZhpqamEeAfkkoTpd2RTVfhYUFUybU4jroswb7E0RVMkCIp-MWUN2yfB_VZUCSczg3dkuqvLipph88kjIixKedt5n0cCNcg49DiwWmM2WZ5IFcy5Lq5GZC0qSyPNO-DXCwppbcZA-BG6_g_f8C75N6dGo-glKFPfDAubRf_UDi3nTcBUaE8kNqGb_sfJRAlzFAsb8ZNCM6D0FjjEb6tJkGRRVlCdjl1aQdWSUNBJF5wM1EkwLqy9pwt2Vz7Vw',
    },
    category: 'Creative Arts',
    rating: 4.2,
    students: '850',
    price: 'KSh 1,800',
    image: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Intermediate',
    duration: '4h 15m',
    tool: 'Figma',
    extraTags: '+7',
  },
  {
    id: '8',
    title: 'Data Analysis for Social Impact',
    instructor: {
      name: 'Dr. Amara Okafor',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-1p4L0MBDscikvxeha4-aMR6PXf6nAxsb-U9haagk8bJCquVyLhcQa3Rfy-d57pZVORzgEYZZHbGCu_iIEVCS6QMzzjVWElnYGH4fHUmLAQgSnAuFQLI9r7xPniCMv5QbftuRDHt90GfPJgeJWSfVpwuHntd_DEOedbcVDcqyjXEZtgtxZGRUlyFpgr0Qohf7G8zK_U2gsApX1ABGep6x801qyKUvhAsDYF-wZKHpCMtm-x3lqudJ-Fa1QCvVxlwS6q9Fr-ANFw',
    },
    category: 'Tech & IT',
    rating: 4.7,
    students: '1.8k',
    price: 'KSh 3,500',
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Advanced',
    duration: '8h 20m',
    tool: 'Python',
    extraTags: '+2',
  },
  {
    id: '9',
    title: 'Leadership in the African Context',
    instructor: {
      name: 'Prof. John Kenyatta',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEze8IgVnbGXtzC8bw2I0bzHuLDsuYHxtzJ0w6EvqrVZACkMcpQu7vRvuBWcJdysGnpnosk8aZvX7mnXBSFFZmyVm7b20_ojXcK2eDxw4-e212eiIytmHa1I6XqU8CKkpxo8NeVHZowa4RID5FlEASug04Yc_M4iXqnMUFpL9cDoEFs9sV89asjL5YlLOqLv8baYYAyBZcTD3YpNgboVVFYXsj5oeMdweQ9NQOmCbIrFXmlWpta1GKW_vWQs2OkyTWMISRTKpjNg',
    },
    category: 'Business & Finance',
    rating: 4.5,
    students: '3.2k',
    price: 'FREE',
    image: 'https://images.pexels.com/photos/3184306/pexels-photo-3184306.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Any level',
    duration: '2h 5m',
    tool: 'Excel',
    extraTags: '+11',
  },
  {
    id: '10',
    title: 'Mastering Mobile Photography',
    instructor: {
      name: 'Fatima Toure',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqhzAtpgYIdyIs_axNU7r4YQenQ4DpP8rgzSsv9hryXQb5vZ_jKOyEnQNX4y7bvJ9OnjlSfNeN-fdDH0gzGBTNf1d63bJUu3J-qe_LHwPQwsOXDz2m1uSGNkaSVI-_f1zia2Vpqn5iF1ANSXMzWpwAD6qx26RZ8sDLgAqvaMF8fzOrW5f4AliH-iQxxOq9Z9jdbk5Z3ZtVjzWljXfLTi30MwTmIitfJO0Thj2LWBBoZBeijeWF7ga8JzbB8ptHZ0Rsi8Wh7Jc4VQ',
    },
    category: 'Creative Arts',
    rating: 4.9,
    students: '5k',
    price: 'KSh 1,200',
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'Beginner',
    duration: '6h 44m',
    tool: 'Adobe CC',
    extraTags: '+23',
  },
];

export interface CareerPath {
  id: string;
  title: string;
  description: string;
  image: string;
  heroImage?: string;
  bgColor: string;
  hoverColor: string;
  heroTextColor: string;
  longDescription?: string;
  skills?: string[];
  salaryRange?: string;
  demand?: string;
}

export const CAREER_PATHS: CareerPath[] = [
  {
    id: 'software-engineer',
    title: 'Software Engineer',
    description: 'Design, develop, and maintain the software systems that power modern African businesses and applications.',
    image: 'https://drive.google.com/thumbnail?id=1T0KrVT1LfAJAuvRhK0gHIX0nO0R2jeTp&sz=w800',
    level: 'Intermediate',
    duration: '12h 30m',
    tool: 'DaVinci Resolve',
    extraTags: '+4',
    heroImage: 'https://drive.google.com/thumbnail?id=1TuNZCZUhiLZif7ZabQRDmCvb7H_PLfMQ&sz=w1200',
    bgColor: '#ffe8d6',
    hoverColor: '#0D79F2',
    heroTextColor: 'text-white',
    longDescription: 'Software Engineering is at the heart of Africa\'s digital transformation. As a software engineer, you will build scalable applications, design robust architectures, and solve complex problems that impact millions of lives. From fintech solutions in Lagos to agritech platforms in Nairobi, the demand for skilled developers has never been higher.',
    skills: ['JavaScript/TypeScript', 'Python', 'React & Node.js', 'System Design', 'Cloud Computing (AWS/GCP)'],
    salaryRange: 'KSh 150,000 - 450,000 / month',
    demand: 'Very High',
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    description: 'Turn complex data into actionable insights for high-impact decision making in global markets.',
    image: 'https://drive.google.com/thumbnail?id=1T4y4ueYUj9lIbtMVdPYrN-C7hmIdGIHg&sz=w800',
    level: 'Advanced',
    duration: '4h 15m',
    tool: 'Procreate',
    extraTags: '+7',
    heroImage: 'https://drive.google.com/thumbnail?id=1I77jmmeK8g7Zc4OpJBAxmaVeg7AvbmS-&sz=w1200',
    bgColor: '#e8f5e9',
    hoverColor: '#50D926',
    heroTextColor: 'text-[#00113a]',
    longDescription: 'Data is the new oil, and Data Scientists are the refiners. In this role, you will analyze vast amounts of structured and unstructured data to uncover hidden patterns, correlations, and insights. You will build predictive models that help businesses optimize their operations, understand customer behavior, and drive strategic growth across the continent.',
    skills: ['Python/R', 'Machine Learning', 'SQL & NoSQL', 'Data Visualization', 'Statistical Analysis'],
    salaryRange: 'KSh 180,000 - 500,000 / month',
    demand: 'High',
  },
  {
    id: 'graphic-design',
    title: 'Graphic Design',
    description: 'Create stunning visual concepts to communicate ideas that inspire, inform, and captivate consumers.',
    image: 'https://drive.google.com/thumbnail?id=1AFmKNvrpoAcBRQDP2BpTZuSjd1CT4LlO&sz=w800',
    level: 'Any level',
    duration: '8h 20m',
    tool: 'Figma',
    extraTags: '+2',
    heroImage: 'https://drive.google.com/thumbnail?id=1hu0Z4CWkRGfpJ6mFTygkhs5WR5hXFGJp&sz=w1200',
    bgColor: '#e3f2fd',
    hoverColor: '#F25E0D',
    heroTextColor: 'text-white',
    longDescription: 'Graphic Design is the art of visual communication. As a designer, you will combine typography, imagery, and color to craft compelling brand identities, marketing materials, and digital experiences. Your work will shape how African brands are perceived globally, blending traditional aesthetics with modern design principles.',
    skills: ['Adobe Creative Suite', 'UI/UX Principles', 'Typography', 'Brand Identity', 'Illustration'],
    salaryRange: 'KSh 80,000 - 250,000 / month',
    demand: 'Medium to High',
  },
  {
    id: 'content-creator',
    title: 'Content Creator',
    description: 'Harness digital platforms to tell compelling stories and build your unique African brand.',
    image: 'https://drive.google.com/thumbnail?id=1sqUyg8NsD6ki8o6xVRw9XF7BiHNNgAAP&sz=w800',
    level: 'Beginner',
    duration: '2h 5m',
    tool: 'Python',
    extraTags: '+11',
    heroImage: 'https://drive.google.com/thumbnail?id=1l_MBGofkWM5bhBw4RuIf36QO2t9_NsAb&sz=w1200',
    bgColor: '#fbe9e7',
    hoverColor: '#FFBF00',
    heroTextColor: 'text-[#00113a]',
    longDescription: 'Content Creation is redefining media and entertainment. Whether through video, audio, or written word, content creators are the new storytellers. You will learn to produce engaging content, build loyal communities, and monetize your digital presence across platforms like YouTube, TikTok, and Instagram, amplifying African voices worldwide.',
    skills: ['Video Editing', 'Copywriting', 'Social Media Strategy', 'Audience Building', 'Analytics'],
    salaryRange: 'Variable (KSh 50,000 - 1M+ / month)',
    demand: 'High',
  },
  {
    id: 'ui-ux-design',
    title: 'UI/UX Design',
    description: 'Design intuitive and engaging user experiences for functional digital products.',
    image: '/skillz-uiux.png',
    level: 'Intermediate',
    duration: '6h 44m',
    tool: 'Excel',
    extraTags: '+23',
    heroImage: '/skillz-uiux-hero.png',
    bgColor: '#fce4ec',
    hoverColor: '#E91E63',
    heroTextColor: 'text-white',
    longDescription: 'UI/UX Design is crucial for the success of digital platforms. As a designer, you will research user behavior, create wireframes and prototypes, and design highly functional interfaces that users love. You will blend aesthetics with usability to create seamless digital journeys.',
    skills: ['Figma / Sketch', 'User Research', 'Prototyping', 'Interaction Design', 'Wireframing'],
    salaryRange: 'KSh 120,000 - 350,000 / month',
    demand: 'High',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    description: 'Lead cross-functional teams to build and scale products that users love.',
    image: '/skillz-pm.png',
    level: 'Advanced',
    duration: '12h 30m',
    tool: 'Adobe CC',
    extraTags: '+4',
    heroImage: '/skillz-pm-hero.png',
    bgColor: '#e8eaf6',
    hoverColor: '#3F51B5',
    heroTextColor: 'text-white',
    longDescription: 'Product Managers are the CEOs of their products. You will guide the success of a product and lead the cross-functional team that is responsible for improving it. You will set strategy, create roadmaps, and define product features that address user needs and meet business goals.',
    skills: ['Product Strategy', 'Agile/Scrum', 'Data Analysis', 'User Research', 'Stakeholder Management'],
    salaryRange: 'KSh 150,000 - 450,000 / month',
    demand: 'Very High',
  },
  {
    id: 'arts-and-craft',
    title: 'Arts and Craft',
    description: 'Express your creativity and build physical and digital art that inspires.',
    image: '/skillz-art-craft.png',
    level: 'Any level',
    duration: '4h 15m',
    tool: 'DaVinci Resolve',
    extraTags: '+7',
    heroImage: '/skillz-art-hero.png',
    bgColor: '#fff3e0',
    hoverColor: '#FF9800',
    heroTextColor: 'text-white',
    longDescription: 'Arts and Craft blends traditional artistic skills with modern creative expressions. You will develop unique pieces, whether for exhibitions, commercial use, or digital media. This field allows you to bring abstract ideas to life through various mediums and techniques.',
    skills: ['Visual Arts', 'Creative Thinking', 'Material Knowledge', 'Design Principles', 'Illustration'],
    salaryRange: 'KSh 50,000 - 200,000 / month',
    demand: 'Medium',
  },
  {
    id: 'finance-auditor',
    title: 'Finance Auditor',
    description: 'Ensure financial integrity and provide strategic insights for business growth.',
    image: '/skillz-auditor.png',
    level: 'Beginner',
    duration: '8h 20m',
    tool: 'Procreate',
    extraTags: '+2',
    heroImage: '/skillz-auditor-hero.png',
    bgColor: '#e0f2f1',
    hoverColor: '#009688',
    heroTextColor: 'text-white',
    longDescription: 'Finance Auditors play a critical role in maintaining the financial health and compliance of organizations. You will examine financial records, ensure accuracy, assess risk management strategies, and recommend improvements that drive business efficiency and trust.',
    skills: ['Financial Analysis', 'Auditing Standards', 'Risk Assessment', 'Accounting', 'Regulatory Compliance'],
    salaryRange: 'KSh 120,000 - 400,000 / month',
    demand: 'High',
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Mary Mbugua',
    role: 'Marketing Lead, Nairobi',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
    content: 'SkillsZone allowed me to pivot into digital marketing without quitting my day job. The instructors are from right here in Kenya, so they understand our market nuances.',
  },
  {
    id: '2',
    name: 'Kwame Owusu',
    role: 'Junior Developer, Accra',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    content: 'The Python course was hands-on and practical. Within three months of finishing, I landed my first internship. The community is supportive and inspiring.',
  },
  {
    id: '3',
    name: 'Fatima Hassan',
    role: 'Entrepreneur, Lagos',
    avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=150',
    content: 'Learning business finance helped me scale my small boutique. I finally understand my numbers, and it\'s all thanks to the expert tutors on this platform.',
  },
];
